// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listDisplays: () => typedError<DisplayInfo[], string>(__TAURI_INVOKE("list_displays")),
	listWindows: () => typedError<WindowInfo[], string>(__TAURI_INVOKE("list_windows")),
	checkPermissions: () => __TAURI_INVOKE<Permissions>("check_permissions"),
	requestPermission: (permission: Permission) => __TAURI_INVOKE<PermissionState>("request_permission", { permission }),
	startRecording: (request: RecordingRequest) => typedError<RecordingStatus, string>(__TAURI_INVOKE("start_recording", { request })),
	recordingStatus: () => typedError<{
	bundlePath: string,
	elapsedMs: number | null,
	width: number,
	height: number,
	/**  False when Input Monitoring is missing, so clicks are not recorded. */
	inputEvents: boolean,
	problems: string[],
} | null, string>(__TAURI_INVOKE("recording_status")),
	stopRecording: () => typedError<FinishedRecording, string>(__TAURI_INVOKE("stop_recording")),
	listUnfinished: () => typedError<UnfinishedBundle[], string>(__TAURI_INVOKE("list_unfinished")),
	recoverBundle: (path: string) => typedError<FinishedRecording, string>(__TAURI_INVOKE("recover_bundle", { path })),
	discardUnfinished: (path: string) => typedError<null, string>(__TAURI_INVOKE("discard_unfinished", { path })),
	revealInFinder: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_finder", { path })),
};

/* Types */
/**  Gains from 0 (muted) to 2. */
export type AudioMix = {
	micVolume?: number | null,
	systemVolume?: number | null,
};

export type AudioTrack = {
	file: string,
	/**  Start of the track relative to the first video frame. */
	offsetMs: number | null,
	durationMs: number | null,
};

export type BackgroundFill = { kind: "solid"; color: Color } | 
/**  `angle_deg` follows CSS: 0 points up, 90 points right. */
{ kind: "gradient"; from: Color; to: Color; angleDeg: number | null } | 
/**  PNG or JPEG, absolute or relative to the bundle. Scaled to cover the frame. */
{ kind: "image"; path: string };

/**  `padding` and `corner_radius` are fractions of the screen's shorter side. */
export type BackgroundSettings = {
	fill?: BackgroundFill,
	padding?: number | null,
	cornerRadius?: number | null,
	shadow?: Shadow,
};

export type CaptureSource = { kind: "display"; displayId: number } | { kind: "window"; windowId: number; title: string | null; appName: string | null } | { kind: "region"; displayId: number; rect: Rect };

export type CaptureTarget = { kind: "display"; displayId: number } | { kind: "window"; windowId: number } | 
/**  `rect` is in points, relative to the display's top-left corner. */
{ kind: "region"; displayId: number; rect: Rect };

export type ClickSettings = {
	ripple?: boolean,
	color?: Color,
	/**  Largest ripple radius, in screen points. */
	size?: number | null,
	squish?: boolean,
};

export type Codec = "h264" | "hevc";

/**  An sRGB color, written as `#rrggbb` or `#rrggbbaa`. */
export type Color = string;

export type CursorSettings = {
	/**  Multiple of the recorded cursor size. */
	size?: number | null,
	/**  0 follows the recorded path exactly; 1 is the smoothest. */
	smoothing?: number | null,
	hideWhenIdle?: boolean,
};

export type DisplayInfo = {
	id: number,
	name: string,
	/**  Global display points. */
	bounds: Rect,
	scaleFactor: number | null,
};

/**
 *  Everything the user can change about a recording. Rendering never alters the
 *  recorded media; these settings are applied at preview and export time.
 */
export type EditSettings = {
	version?: number,
	background?: BackgroundSettings,
	cursor?: CursorSettings,
	zoom?: ZoomSettings,
	clicks?: ClickSettings,
	sounds?: SoundSettings,
	audio?: AudioMix,
	trim?: Trim,
	export?: ExportSettings,
};

export type ExportSettings = {
	codec?: Codec,
	resolution?: Resolution,
	fps?: FrameRate,
	/**  0..1, mapped to the encoder bitrate. */
	quality?: number | null,
};

export type FinishedRecording = {
	bundlePath: string,
	project: Project,
	/**  Problems that did not prevent saving, such as the capture stopping on its own. */
	warnings: string[],
};

export type FrameRate = "30" | "60";

export type Permission = "screenRecording" | "inputMonitoring" | "microphone";

export type PermissionState = "granted" | "denied" | "notDetermined";

export type Permissions = {
	screenRecording: PermissionState,
	inputMonitoring: PermissionState,
	microphone: PermissionState,
};

export type Project = {
	version: number,
	name: string,
	createdAtUnixMs: number | null,
	recording: Recording,
	edits?: EditSettings,
};

export type Recording = {
	source: CaptureSource,
	/**  Captured area in global display points; input events use the same space. */
	bounds: Rect,
	width: number,
	height: number,
	scaleFactor: number | null,
	fps: number,
	durationMs: number | null,
	video: VideoTrack,
	systemAudio: AudioTrack | null,
	mic: AudioTrack | null,
	eventsFile: string,
	cursorsDir: string,
	recovered: boolean,
};

export type RecordingRequest = {
	target: CaptureTarget,
	systemAudio: boolean,
	mic: boolean,
};

export type RecordingStatus = {
	bundlePath: string,
	elapsedMs: number | null,
	width: number,
	height: number,
	/**  False when Input Monitoring is missing, so clicks are not recorded. */
	inputEvents: boolean,
	problems: string[],
};

export type Rect = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**  The output's shorter side. */
export type Resolution = "1080p" | "1440p" | "4k";

/**  Sizes are fractions of the screen's shorter side. */
export type Shadow = {
	opacity?: number | null,
	blur?: number | null,
	offsetY?: number | null,
};

export type SoundPack = "softTap" | "mouseClick" | "mechanical";

export type SoundSettings = {
	enabled?: boolean,
	pack?: SoundPack,
	/**  0..1 */
	volume?: number | null,
	/**  Right clicks use the pack's own right-button sounds instead of the left ones. */
	separateLeftRight?: boolean,
};

/**  Milliseconds on the recording's timeline; no `end_ms` means the end of the recording. */
export type Trim = {
	startMs?: number | null,
	endMs?: number | null,
};

export type UnfinishedBundle = {
	path: string,
	name: string,
	startedAtUnixMs: number | null,
	/**  Why recovery cannot work, e.g. the recorder stopped before the first video fragment. */
	problem: string | null,
};

export type VideoTrack = {
	file: string,
	codec: string,
	durationMs: number | null,
};

export type WindowInfo = {
	id: number,
	title: string,
	appName: string,
	/**  Global display points. */
	bounds: Rect,
};

export type ZoomFocus = { kind: "followCursor" } | 
/**  Normalized position on the screen, 0..1 from the top-left corner. */
{ kind: "point"; x: number | null; y: number | null };

export type ZoomSegment = {
	startMs: number | null,
	endMs: number | null,
	level: number | null,
	focus: ZoomFocus,
};

/**  With `auto` on, segments are generated from clicks and `segments` is ignored. */
export type ZoomSettings = {
	auto?: boolean,
	level?: number | null,
	segments?: ZoomSegment[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

