// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	checkPermissions: () => __TAURI_INVOKE<Permissions>("check_permissions"),
	requestPermission: (permission: Permission) => __TAURI_INVOKE<PermissionState>("request_permission", { permission }),
	openPrivacySettings: (permission: Permission) => typedError<null, string>(__TAURI_INVOKE("open_privacy_settings", { permission })),
	/**  Quits and opens Recast again through Launch Services. */
	relaunch: () => typedError<null, string>(__TAURI_INVOKE("relaunch")),
	/**  Remembers that onboarding is done and closes its window. */
	completeOnboarding: () => typedError<AppSettings, string>(__TAURI_INVOKE("complete_onboarding")),
	/**
	 *  Picks a target with `mode` and starts recording it, after the countdown when that
	 *  is on.
	 */
	startRecording: (mode: PickMode) => typedError<null, string>(__TAURI_INVOKE("start_recording", { mode })),
	/**  Picks a target with `mode` and takes a screenshot of it; `None` when cancelled. */
	takeScreenshot: (mode: PickMode) => typedError<{
	/**  The saved file, when saving is on. */
	path: string | null,
	width: number,
	height: number,
	copied: boolean,
	/**  Problems that didn't stop the capture, such as a failed clipboard copy. */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("take_screenshot", { mode })),
	stopRecording: () => __TAURI_INVOKE<void>("stop_recording"),
	recordingPhase: () => typedError<Phase, string>(__TAURI_INVOKE("recording_phase")),
	listUnfinished: () => typedError<UnfinishedBundle[], string>(__TAURI_INVOKE("list_unfinished")),
	recoverBundle: (path: string) => typedError<FinishedRecording, string>(__TAURI_INVOKE("recover_bundle", { path })),
	discardUnfinished: (path: string) => typedError<null, string>(__TAURI_INVOKE("discard_unfinished", { path })),
	revealInFinder: (path: string) => __TAURI_INVOKE<void>("reveal_in_finder", { path }),
	openRecordingsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_recordings_folder")),
	openWindow: (window: AppWindow) => typedError<null, string>(__TAURI_INVOKE("open_window", { window })),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	setScreenshotSettings: (screenshots: ScreenshotSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("set_screenshot_settings", { screenshots })),
	setRecordingSettings: (recording: RecordingSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("set_recording_settings", { recording })),
	setUpdateSettings: (updates: UpdateSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("set_update_settings", { updates })),
	/**
	 *  Changes an action's shortcut, `None` turning it off. A conflict is an error and
	 *  changes nothing; a shortcut macOS refuses is kept and reported in its status.
	 */
	setShortcut: (action: ShortcutAction, shortcut: string | null) => typedError<ShortcutStatus[], string>(__TAURI_INVOKE("set_shortcut", { action, shortcut })),
	shortcutStatuses: () => __TAURI_INVOKE<ShortcutStatus[]>("shortcut_statuses"),
	/**  Turns the global shortcuts off while the Settings window records a new one. */
	suspendShortcuts: (suspended: boolean) => __TAURI_INVOKE<ShortcutStatus[]>("suspend_shortcuts", { suspended }),
	getLaunchAtLogin: () => __TAURI_INVOKE<LoginItem>("get_launch_at_login"),
	setLaunchAtLogin: (enabled: boolean) => typedError<LoginItem, string>(__TAURI_INVOKE("set_launch_at_login", { enabled })),
	openLoginItemsSettings: () => __TAURI_INVOKE<void>("open_login_items_settings"),
	checkForUpdates: () => __TAURI_INVOKE<void>("check_for_updates"),
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	openLogsFolder: () => __TAURI_INVOKE<void>("open_logs_folder"),
	copyDiagnostics: () => typedError<null, string>(__TAURI_INVOKE("copy_diagnostics")),
	listScreenshots: () => typedError<ScreenshotSummary[], string>(__TAURI_INVOKE("list_screenshots")),
	editScreenshot: (path: string) => typedError<null, string>(__TAURI_INVOKE("edit_screenshot", { path })),
	markupOpen: () => typedError<MarkupInit, string>(__TAURI_INVOKE("markup_open")),
	/**
	 *  The Beautify frame around a `width × height` image, without the image, scaled to fit
	 *  `max_width × max_height` pixels.
	 */
	markupFrame: (background: BackgroundSettings, width: number, height: number, maxWidth: number, maxHeight: number) => typedError<MarkupFrame, string>(__TAURI_INVOKE("markup_frame", { background, width, height, maxWidth, maxHeight })),
	/**
	 *  Finishes the image staged with `staged`, or the original screenshot when it is `None`,
	 *  with Beautify when `background` is given. Returns the file written, if any.
	 */
	markupFinish: (action: MarkupAction, staged: number | null, background: {
	fill?: BackgroundFill,
	padding?: number | null,
	cornerRadius?: number | null,
	shadow?: Shadow,
} | null) => typedError<string | null, string>(__TAURI_INVOKE("markup_finish", { action, staged, background })),
	/**  Moves the screenshot to the Trash and closes the window. */
	markupDiscard: () => typedError<null, string>(__TAURI_INVOKE("markup_discard")),
	listProjects: () => typedError<ProjectSummary[], string>(__TAURI_INVOKE("list_projects")),
	openEditor: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_editor", { path })),
	/**  Starts the session of the calling editor window (or returns the running one). */
	editorOpen: () => typedError<EditorInit, string>(__TAURI_INVOKE("editor_open")),
	/**
	 *  Applies edits to the preview and saves them; returns the auto zoom segments.
	 *  `seq` increases with every call; a call that arrives after a newer one is
	 *  ignored and returns `None`.
	 */
	editorSetSettings: (settings: EditSettings, seq: number) => typedError<ZoomSegment[] | null, string>(__TAURI_INVOKE("editor_set_settings", { settings, seq })),
	editorPlay: () => typedError<null, string>(__TAURI_INVOKE("editor_play")),
	editorPause: () => typedError<null, string>(__TAURI_INVOKE("editor_pause")),
	editorSeek: (tMs: number | null, seq: number) => typedError<null, string>(__TAURI_INVOKE("editor_seek", { tMs, seq })),
	editorSetLoop: (looping: boolean) => typedError<null, string>(__TAURI_INVOKE("editor_set_loop", { looping })),
	/**  The preview's drawing area in device pixels. */
	editorResize: (width: number, height: number) => typedError<null, string>(__TAURI_INVOKE("editor_resize", { width, height })),
	editorStatus: () => typedError<EditorStatus, string>(__TAURI_INVOKE("editor_status")),
	editorStats: () => typedError<PreviewStats, string>(__TAURI_INVOKE("editor_stats")),
	/**
	 *  Exports the project with its current edits to `output_path`. Progress and the
	 *  result arrive as `ExportProgress` and `ExportFinished` events.
	 */
	exportStart: (outputPath: string) => typedError<null, string>(__TAURI_INVOKE("export_start", { outputPath })),
	exportCancel: () => typedError<null, string>(__TAURI_INVOKE("export_cancel")),
	/**  A WAV file with the pack's click sound, for previewing it. */
	clickSoundPreview: (pack: SoundPack) => __TAURI_INVOKE<number[]>("click_sound_preview", { pack }),
};

/** Events */
export const events = {
	exportFinished: makeEvent<ExportFinished>("export-finished"),
	exportProgress: makeEvent<ExportProgress>("export-progress"),
	recordingChanged: makeEvent<RecordingChanged>("recording-changed"),
};

/* Types */
export type AppInfo = {
	version: string,
	logsDir: string,
};

export type AppSettings = {
	version?: number,
	screenshots?: ScreenshotSettings,
	/**  The last Beautify background used in the markup editor. */
	beautify?: BackgroundSettings,
	recording?: RecordingSettings,
	shortcuts?: ShortcutSettings,
	updates?: UpdateSettings,
	onboardingCompleted?: boolean,
};

export type AppWindow = "library" | "settings" | "onboarding";

/**  Gains from 0 (muted) to 2. */
export type AudioMix = {
	micVolume?: number | null,
	systemVolume?: number | null,
};

export type AudioTrack = {
	file: string,
	/**  Start of the track relative to the first video frame. */
	offsetMs: number | null,
	durationMs: number | null,
};

export type BackgroundFill = { kind: "solid"; color: Color } | 
/**  `angle_deg` follows CSS: 0 points up, 90 points right. */
{ kind: "gradient"; from: Color; to: Color; angleDeg: number | null } | 
/**  PNG or JPEG, absolute or relative to the bundle. Scaled to cover the frame. */
{ kind: "image"; path: string };

/**  `padding` and `corner_radius` are fractions of the screen's shorter side. */
export type BackgroundSettings = {
	fill?: BackgroundFill,
	padding?: number | null,
	cornerRadius?: number | null,
	shadow?: Shadow,
};

export type CaptureSource = { kind: "display"; displayId: number } | { kind: "window"; windowId: number; title: string | null; appName: string | null } | { kind: "region"; displayId: number; rect: Rect };

export type ClickMarker = {
	tMs: number | null,
	button: MouseButton,
};

export type ClickSettings = {
	ripple?: boolean,
	color?: Color,
	/**  Largest ripple radius, in screen points. */
	size?: number | null,
	squish?: boolean,
};

export type Codec = "h264" | "hevc";

/**  An sRGB color, written as `#rrggbb` or `#rrggbbaa`. */
export type Color = string;

export type CursorSettings = {
	/**  Multiple of the recorded cursor size. */
	size?: number | null,
	/**  0 follows the recorded path exactly; 1 is the smoothest. */
	smoothing?: number | null,
	hideWhenIdle?: boolean,
};

/**
 *  Everything the user can change about a recording. Rendering never alters the
 *  recorded media; these settings are applied at preview and export time.
 */
export type EditSettings = {
	version?: number,
	background?: BackgroundSettings,
	cursor?: CursorSettings,
	zoom?: ZoomSettings,
	clicks?: ClickSettings,
	sounds?: SoundSettings,
	audio?: AudioMix,
	trim?: Trim,
	export?: ExportSettings,
};

export type EditorInit = {
	bundlePath: string,
	project: Project,
	/**  The saved edits, with every value in range. */
	settings: EditSettings,
	durationMs: number | null,
	/**  Segments auto zoom generates at the saved zoom level. */
	autoSegments: ZoomSegment[],
	/**  Button presses inside the recorded area. */
	clicks: ClickMarker[],
	/**  WebSocket URL of the preview stream, including its token. */
	previewUrl: string,
	/**  Suggested path for an export. */
	exportPath: string,
};

export type EditorStatus = {
	playing: boolean,
	positionMs: number | null,
	error: string | null,
};

export type ExportFinished = {
	bundlePath: string,
	outputPath: string,
	cancelled: boolean,
	error: string | null,
};

export type ExportProgress = {
	bundlePath: string,
	frame: number,
	totalFrames: number,
};

export type ExportSettings = {
	codec?: Codec,
	resolution?: Resolution,
	fps?: FrameRate,
	/**  0..1, mapped to the encoder bitrate. */
	quality?: number | null,
};

export type FinishedRecording = {
	bundlePath: string,
	project: Project,
	/**  Problems that did not prevent saving, such as the capture stopping on its own. */
	warnings: string[],
};

export type FrameRate = "30" | "60";

export type LoginItem = "enabled" | "disabled" | 
/**  The user has to allow it in System Settings → General → Login Items. */
"needsApproval";

export type MarkupAction = { kind: "copy" } | { kind: "saveAs"; path: string } | 
/**  Writes over the screenshot's file and closes the window. */
{ kind: "done" };

export type MarkupFrame = {
	/**  PNG data URL. */
	url: string,
	width: number,
	height: number,
};

export type MarkupInit = {
	name: string,
	width: number,
	height: number,
	scaleFactor: number | null,
	/**  The Beautify background used last time. */
	background: BackgroundSettings,
};

export type MouseButton = "left" | "right" | "other";

export type Permission = "screenRecording" | "inputMonitoring" | "microphone";

export type PermissionState = "granted" | "denied" | "notDetermined";

export type Permissions = {
	screenRecording: PermissionState,
	inputMonitoring: PermissionState,
	microphone: PermissionState,
};

export type Phase = { kind: "idle" } | { kind: "picking" } | { kind: "countdown" } | 
/**  The countdown is over and capture is starting. */
{ kind: "starting" } | { kind: "recording"; elapsedMs: number | null } | { kind: "stopping" };

/**  What the picker picks. Each mode picks one kind of target only. */
export type PickMode = 
/**  A drag selects a region; clicks do nothing. */
"area" | 
/**  The window under the pointer is highlighted; a click picks it. */
"window" | 
/**  The display under the pointer is highlighted; a click picks it. */
"display";

export type PreviewStats = {
	frames: number,
	renderMs: number | null,
	lastSeekMs: number | null,
	width: number,
	height: number,
	dropped: number,
	/**  Whether audio plays on an output device; `None` while it is being opened. */
	audioOutput: boolean | null,
};

export type Project = {
	version: number,
	name: string,
	createdAtUnixMs: number | null,
	recording: Recording,
	edits?: EditSettings,
};

export type ProjectSummary = {
	path: string,
	name: string,
	createdAtUnixMs: number | null,
	durationMs: number | null,
	width: number,
	height: number,
};

export type Recording = {
	source: CaptureSource,
	/**  Captured area in global display points; input events use the same space. */
	bounds: Rect,
	width: number,
	height: number,
	scaleFactor: number | null,
	fps: number,
	durationMs: number | null,
	video: VideoTrack,
	systemAudio: AudioTrack | null,
	mic: AudioTrack | null,
	eventsFile: string,
	cursorsDir: string,
	recovered: boolean,
};

export type RecordingChanged = {
	phase: Phase,
};

export type RecordingSettings = {
	/**  Counts down from 3 before recording starts. */
	countdown?: boolean,
	mic?: boolean,
	systemAudio?: boolean,
	/**  Where recordings are saved; `None` means `~/Movies/Recast`. */
	folder?: string | null,
};

export type Rect = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**
 *  The output size: the recording at its own pixel size, or a preset for the output's
 *  shorter side.
 */
export type Resolution = "auto" | "1080p" | "1440p" | "4k";

export type ScreenshotSettings = {
	copyToClipboard?: boolean,
	saveToDisk?: boolean,
	/**  Where captures are saved; `None` means `~/Pictures/Recast`. */
	folder?: string | null,
	playShutterSound?: boolean,
};

/**  A saved screenshot, for the Library and Recent Screenshots. */
export type ScreenshotSummary = {
	path: string,
	/**  File name without the extension. */
	name: string,
	modifiedAtUnixMs: number | null,
	width: number,
	height: number,
};

export type ScreenshotTaken = {
	/**  The saved file, when saving is on. */
	path: string | null,
	width: number,
	height: number,
	copied: boolean,
	/**  Problems that didn't stop the capture, such as a failed clipboard copy. */
	warnings: string[],
};

/**  Sizes are fractions of the screen's shorter side. */
export type Shadow = {
	opacity?: number | null,
	blur?: number | null,
	offsetY?: number | null,
};

export type ShortcutAction = "recordArea" | "recordWindow" | "recordDisplay" | "captureArea" | "captureWindow" | "captureDisplay";

/**  Global shortcuts in the form `Alt+Shift+Cmd+KeyR`; `None` turns one off. */
export type ShortcutSettings = {
	recordArea?: string | null,
	recordWindow?: string | null,
	recordDisplay?: string | null,
	captureArea?: string | null,
	captureWindow?: string | null,
	captureDisplay?: string | null,
};

export type ShortcutStatus = {
	action: ShortcutAction,
	/**  The stored shortcut, `None` when turned off. */
	shortcut: string | null,
	/**  How macOS shows it, such as `⌥⇧⌘R`. */
	symbols: string | null,
	/**  Why it doesn't work: a conflict or macOS refusing to register it. */
	error: string | null,
};

export type SoundPack = "softTap" | "mouseClick" | "mechanical" | "trackpadTap" | "pop" | "tick";

export type SoundSettings = {
	enabled?: boolean,
	pack?: SoundPack,
	/**  0..1 */
	volume?: number | null,
	/**  Right clicks use the pack's own right-button sounds instead of the left ones. */
	separateLeftRight?: boolean,
};

/**  Milliseconds on the recording's timeline; no `end_ms` means the end of the recording. */
export type Trim = {
	startMs?: number | null,
	endMs?: number | null,
};

export type UnfinishedBundle = {
	path: string,
	name: string,
	startedAtUnixMs: number | null,
	/**  Why recovery cannot work, e.g. the recorder stopped before the first video fragment. */
	problem: string | null,
};

export type UpdateSettings = {
	checkAutomatically?: boolean,
};

export type VideoTrack = {
	file: string,
	codec: string,
	durationMs: number | null,
};

export type ZoomFocus = { kind: "followCursor" } | 
/**  Normalized position on the screen, 0..1 from the top-left corner. */
{ kind: "point"; x: number | null; y: number | null };

export type ZoomSegment = {
	startMs: number | null,
	endMs: number | null,
	level: number | null,
	focus: ZoomFocus,
};

/**  With `auto` on, segments are generated from clicks and `segments` is ignored. */
export type ZoomSettings = {
	auto?: boolean,
	level?: number | null,
	segments?: ZoomSegment[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

