// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listDisplays: () => typedError<DisplayInfo[], string>(__TAURI_INVOKE("list_displays")),
	listWindows: () => typedError<WindowInfo[], string>(__TAURI_INVOKE("list_windows")),
	checkPermissions: () => __TAURI_INVOKE<Permissions>("check_permissions"),
	requestPermission: (permission: Permission) => __TAURI_INVOKE<PermissionState>("request_permission", { permission }),
	startRecording: (request: RecordingRequest) => typedError<RecordingStatus, string>(__TAURI_INVOKE("start_recording", { request })),
	recordingStatus: () => typedError<{
	bundlePath: string,
	elapsedMs: number | null,
	width: number,
	height: number,
	/**  False when Input Monitoring is missing, so clicks are not recorded. */
	inputEvents: boolean,
	problems: string[],
} | null, string>(__TAURI_INVOKE("recording_status")),
	stopRecording: () => typedError<FinishedRecording, string>(__TAURI_INVOKE("stop_recording")),
	listUnfinished: () => typedError<UnfinishedBundle[], string>(__TAURI_INVOKE("list_unfinished")),
	recoverBundle: (path: string) => typedError<FinishedRecording, string>(__TAURI_INVOKE("recover_bundle", { path })),
	discardUnfinished: (path: string) => typedError<null, string>(__TAURI_INVOKE("discard_unfinished", { path })),
	revealInFinder: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_finder", { path })),
	getSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_settings")),
	setScreenshotSettings: (screenshots: ScreenshotSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("set_screenshot_settings", { screenshots })),
	pickTarget: (mode: PickMode) => typedError<{
	target: CaptureTarget,
	/**  The display the target was picked on. */
	displayId: number,
	/**  The picked area in global points. */
	bounds: Rect,
	label: string,
} | null, string>(__TAURI_INVOKE("pick_target", { mode })),
	/**  Picks a target, captures it and shows the thumbnail; `None` when the user cancels. */
	takeScreenshot: (mode: PickMode) => typedError<{
	/**  The saved file, when saving is on. */
	path: string | null,
	width: number,
	height: number,
	copied: boolean,
	/**  Problems that didn't stop the capture, such as a failed clipboard copy. */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("take_screenshot", { mode })),
	beautifyOpen: () => typedError<BeautifyInit, string>(__TAURI_INVOKE("beautify_open")),
	/**  The beautified screenshot scaled to fit `max_width × max_height` pixels, as a PNG data URL. */
	beautifyPreview: (background: BackgroundSettings, maxWidth: number, maxHeight: number) => typedError<string, string>(__TAURI_INVOKE("beautify_preview", { background, maxWidth, maxHeight })),
	beautifyCopy: (background: BackgroundSettings) => typedError<null, string>(__TAURI_INVOKE("beautify_copy", { background })),
	/**
	 *  Saves to `path`, or under a new name in `~/Pictures/Recast` when there is none.
	 *  Returns the saved file.
	 */
	beautifySave: (background: BackgroundSettings, path: string | null) => typedError<string, string>(__TAURI_INVOKE("beautify_save", { background, path })),
	listProjects: () => __TAURI_INVOKE<ProjectSummary[]>("list_projects"),
	openEditor: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_editor", { path })),
	/**  Starts the session of the calling editor window (or returns the running one). */
	editorOpen: () => typedError<EditorInit, string>(__TAURI_INVOKE("editor_open")),
	/**
	 *  Applies edits to the preview and saves them; returns the auto zoom segments.
	 *  `seq` increases with every call; a call that arrives after a newer one is
	 *  ignored and returns `None`.
	 */
	editorSetSettings: (settings: EditSettings, seq: number) => typedError<ZoomSegment[] | null, string>(__TAURI_INVOKE("editor_set_settings", { settings, seq })),
	editorPlay: () => typedError<null, string>(__TAURI_INVOKE("editor_play")),
	editorPause: () => typedError<null, string>(__TAURI_INVOKE("editor_pause")),
	editorSeek: (tMs: number | null, seq: number) => typedError<null, string>(__TAURI_INVOKE("editor_seek", { tMs, seq })),
	editorSetLoop: (looping: boolean) => typedError<null, string>(__TAURI_INVOKE("editor_set_loop", { looping })),
	/**  The preview's drawing area in device pixels. */
	editorResize: (width: number, height: number) => typedError<null, string>(__TAURI_INVOKE("editor_resize", { width, height })),
	editorStatus: () => typedError<EditorStatus, string>(__TAURI_INVOKE("editor_status")),
	editorStats: () => typedError<PreviewStats, string>(__TAURI_INVOKE("editor_stats")),
	/**
	 *  Exports the project with its current edits to `output_path`. Progress and the
	 *  result arrive as `ExportProgress` and `ExportFinished` events.
	 */
	exportStart: (outputPath: string) => typedError<null, string>(__TAURI_INVOKE("export_start", { outputPath })),
	exportCancel: () => typedError<null, string>(__TAURI_INVOKE("export_cancel")),
};

/** Events */
export const events = {
	exportFinished: makeEvent<ExportFinished>("export-finished"),
	exportProgress: makeEvent<ExportProgress>("export-progress"),
};

/* Types */
export type AppSettings = {
	screenshots?: ScreenshotSettings,
	/**  The last background used to beautify a screenshot. */
	beautify?: BackgroundSettings,
};

/**  Gains from 0 (muted) to 2. */
export type AudioMix = {
	micVolume?: number | null,
	systemVolume?: number | null,
};

export type AudioTrack = {
	file: string,
	/**  Start of the track relative to the first video frame. */
	offsetMs: number | null,
	durationMs: number | null,
};

export type BackgroundFill = { kind: "solid"; color: Color } | 
/**  `angle_deg` follows CSS: 0 points up, 90 points right. */
{ kind: "gradient"; from: Color; to: Color; angleDeg: number | null } | 
/**  PNG or JPEG, absolute or relative to the bundle. Scaled to cover the frame. */
{ kind: "image"; path: string };

/**  `padding` and `corner_radius` are fractions of the screen's shorter side. */
export type BackgroundSettings = {
	fill?: BackgroundFill,
	padding?: number | null,
	cornerRadius?: number | null,
	shadow?: Shadow,
};

export type BeautifyInit = {
	name: string,
	width: number,
	height: number,
	scaleFactor: number | null,
	/**  The background used last time. */
	background: BackgroundSettings,
	savedPath: string | null,
};

export type CaptureSource = { kind: "display"; displayId: number } | { kind: "window"; windowId: number; title: string | null; appName: string | null } | { kind: "region"; displayId: number; rect: Rect };

export type CaptureTarget = { kind: "display"; displayId: number } | { kind: "window"; windowId: number } | 
/**  `rect` is in points, relative to the display's top-left corner. */
{ kind: "region"; displayId: number; rect: Rect };

export type ClickMarker = {
	tMs: number | null,
	button: MouseButton,
};

export type ClickSettings = {
	ripple?: boolean,
	color?: Color,
	/**  Largest ripple radius, in screen points. */
	size?: number | null,
	squish?: boolean,
};

export type Codec = "h264" | "hevc";

/**  An sRGB color, written as `#rrggbb` or `#rrggbbaa`. */
export type Color = string;

export type CursorSettings = {
	/**  Multiple of the recorded cursor size. */
	size?: number | null,
	/**  0 follows the recorded path exactly; 1 is the smoothest. */
	smoothing?: number | null,
	hideWhenIdle?: boolean,
};

export type DisplayInfo = {
	id: number,
	name: string,
	/**  Global display points. */
	bounds: Rect,
	scaleFactor: number | null,
};

/**
 *  Everything the user can change about a recording. Rendering never alters the
 *  recorded media; these settings are applied at preview and export time.
 */
export type EditSettings = {
	version?: number,
	background?: BackgroundSettings,
	cursor?: CursorSettings,
	zoom?: ZoomSettings,
	clicks?: ClickSettings,
	sounds?: SoundSettings,
	audio?: AudioMix,
	trim?: Trim,
	export?: ExportSettings,
};

export type EditorInit = {
	bundlePath: string,
	project: Project,
	/**  The saved edits, with every value in range. */
	settings: EditSettings,
	durationMs: number | null,
	/**  Segments auto zoom generates at the saved zoom level. */
	autoSegments: ZoomSegment[],
	/**  Button presses inside the recorded area. */
	clicks: ClickMarker[],
	/**  WebSocket URL of the preview stream, including its token. */
	previewUrl: string,
	/**  Suggested path for an export. */
	exportPath: string,
};

export type EditorStatus = {
	playing: boolean,
	positionMs: number | null,
	error: string | null,
};

export type ExportFinished = {
	bundlePath: string,
	outputPath: string,
	cancelled: boolean,
	error: string | null,
};

export type ExportProgress = {
	bundlePath: string,
	frame: number,
	totalFrames: number,
};

export type ExportSettings = {
	codec?: Codec,
	resolution?: Resolution,
	fps?: FrameRate,
	/**  0..1, mapped to the encoder bitrate. */
	quality?: number | null,
};

export type FinishedRecording = {
	bundlePath: string,
	project: Project,
	/**  Problems that did not prevent saving, such as the capture stopping on its own. */
	warnings: string[],
};

export type FrameRate = "30" | "60";

export type MouseButton = "left" | "right" | "other";

export type Permission = "screenRecording" | "inputMonitoring" | "microphone";

export type PermissionState = "granted" | "denied" | "notDetermined";

export type Permissions = {
	screenRecording: PermissionState,
	inputMonitoring: PermissionState,
	microphone: PermissionState,
};

/**  What the picker highlights first; Space switches to and from [`PickMode::Display`]. */
export type PickMode = 
/**  Nothing is highlighted until a drag selects a region. */
"area" | 
/**  The window under the pointer is highlighted; a click picks it. */
"window" | 
/**  The display under the pointer is highlighted; a click picks it. */
"display";

export type Picked = {
	target: CaptureTarget,
	/**  The display the target was picked on. */
	displayId: number,
	/**  The picked area in global points. */
	bounds: Rect,
	label: string,
};

export type PreviewStats = {
	frames: number,
	renderMs: number | null,
	lastSeekMs: number | null,
	width: number,
	height: number,
	dropped: number,
	/**  Whether audio plays on an output device; `None` while it is being opened. */
	audioOutput: boolean | null,
};

export type Project = {
	version: number,
	name: string,
	createdAtUnixMs: number | null,
	recording: Recording,
	edits?: EditSettings,
};

export type ProjectSummary = {
	path: string,
	name: string,
	createdAtUnixMs: number | null,
	durationMs: number | null,
	width: number,
	height: number,
};

export type Recording = {
	source: CaptureSource,
	/**  Captured area in global display points; input events use the same space. */
	bounds: Rect,
	width: number,
	height: number,
	scaleFactor: number | null,
	fps: number,
	durationMs: number | null,
	video: VideoTrack,
	systemAudio: AudioTrack | null,
	mic: AudioTrack | null,
	eventsFile: string,
	cursorsDir: string,
	recovered: boolean,
};

export type RecordingRequest = {
	target: CaptureTarget,
	systemAudio: boolean,
	mic: boolean,
};

export type RecordingStatus = {
	bundlePath: string,
	elapsedMs: number | null,
	width: number,
	height: number,
	/**  False when Input Monitoring is missing, so clicks are not recorded. */
	inputEvents: boolean,
	problems: string[],
};

export type Rect = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**  The output's shorter side. */
export type Resolution = "1080p" | "1440p" | "4k";

export type ScreenshotSettings = {
	copyToClipboard?: boolean,
	/**  Saves every capture to `~/Pictures/Recast`. */
	saveToDisk?: boolean,
};

export type ScreenshotTaken = {
	/**  The saved file, when saving is on. */
	path: string | null,
	width: number,
	height: number,
	copied: boolean,
	/**  Problems that didn't stop the capture, such as a failed clipboard copy. */
	warnings: string[],
};

/**  Sizes are fractions of the screen's shorter side. */
export type Shadow = {
	opacity?: number | null,
	blur?: number | null,
	offsetY?: number | null,
};

export type SoundPack = "softTap" | "mouseClick" | "mechanical";

export type SoundSettings = {
	enabled?: boolean,
	pack?: SoundPack,
	/**  0..1 */
	volume?: number | null,
	/**  Right clicks use the pack's own right-button sounds instead of the left ones. */
	separateLeftRight?: boolean,
};

/**  Milliseconds on the recording's timeline; no `end_ms` means the end of the recording. */
export type Trim = {
	startMs?: number | null,
	endMs?: number | null,
};

export type UnfinishedBundle = {
	path: string,
	name: string,
	startedAtUnixMs: number | null,
	/**  Why recovery cannot work, e.g. the recorder stopped before the first video fragment. */
	problem: string | null,
};

export type VideoTrack = {
	file: string,
	codec: string,
	durationMs: number | null,
};

export type WindowInfo = {
	id: number,
	title: string,
	appName: string,
	/**  Global display points. */
	bounds: Rect,
};

export type ZoomFocus = { kind: "followCursor" } | 
/**  Normalized position on the screen, 0..1 from the top-left corner. */
{ kind: "point"; x: number | null; y: number | null };

export type ZoomSegment = {
	startMs: number | null,
	endMs: number | null,
	level: number | null,
	focus: ZoomFocus,
};

/**  With `auto` on, segments are generated from clicks and `segments` is ignored. */
export type ZoomSettings = {
	auto?: boolean,
	level?: number | null,
	segments?: ZoomSegment[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

