//! Click sound packs. The bundled WAVs in `assets/sounds` are generated by
//! [`synthesize`] (`make sounds`), so they carry no third-party license.

use std::io::Cursor;

use recast_project::{MouseButton, SoundPack};
use symphonia::core::{
    codecs::audio::AudioDecoderOptions,
    formats::{FormatOptions, TrackType, probe::Hint},
    io::MediaSourceStream,
    meta::MetadataOptions,
};

use crate::{Error, Result, SAMPLE_RATE};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SoundKind {
    LeftDown,
    LeftUp,
    RightDown,
    RightUp,
}

impl SoundKind {
    pub const ALL: [SoundKind; 4] = [Self::LeftDown, Self::LeftUp, Self::RightDown, Self::RightUp];

    pub fn file_name(self) -> &'static str {
        match self {
            Self::LeftDown => "left-down.wav",
            Self::LeftUp => "left-up.wav",
            Self::RightDown => "right-down.wav",
            Self::RightUp => "right-up.wav",
        }
    }

    pub fn for_click(button: MouseButton, down: bool, separate_right: bool) -> Self {
        let right = separate_right && button == MouseButton::Right;
        match (right, down) {
            (false, true) => Self::LeftDown,
            (false, false) => Self::LeftUp,
            (true, true) => Self::RightDown,
            (true, false) => Self::RightUp,
        }
    }
}

macro_rules! pack_files {
    ($dir:literal) => {
        [
            include_bytes!(concat!("../assets/sounds/", $dir, "/left-down.wav")).as_slice(),
            include_bytes!(concat!("../assets/sounds/", $dir, "/left-up.wav")).as_slice(),
            include_bytes!(concat!("../assets/sounds/", $dir, "/right-down.wav")).as_slice(),
            include_bytes!(concat!("../assets/sounds/", $dir, "/right-up.wav")).as_slice(),
        ]
    };
}

/// The bundled WAV file of a sound.
pub fn bundled(pack: SoundPack, kind: SoundKind) -> &'static [u8] {
    let files = match pack {
        SoundPack::SoftTap => pack_files!("soft-tap"),
        SoundPack::MouseClick => pack_files!("mouse-click"),
        SoundPack::Mechanical => pack_files!("mechanical"),
        SoundPack::TrackpadTap => pack_files!("trackpad-tap"),
        SoundPack::Pop => pack_files!("pop"),
        SoundPack::Tick => pack_files!("tick"),
    };
    let index = SoundKind::ALL
        .iter()
        .position(|k| *k == kind)
        .expect("every kind is listed");
    files[index]
}

/// Decodes an audio file to interleaved stereo at 48 kHz.
pub fn decode(bytes: &[u8], extension: &str) -> Result<Vec<f32>> {
    let fail = |e: symphonia::core::errors::Error| Error::Audio(format!("sound: {e}"));
    let stream = MediaSourceStream::new(Box::new(Cursor::new(bytes.to_vec())), Default::default());
    let mut hint = Hint::new();
    hint.with_extension(extension);
    let mut format = symphonia::default::get_probe()
        .probe(
            &hint,
            stream,
            FormatOptions::default(),
            MetadataOptions::default(),
        )
        .map_err(fail)?;
    let track = format
        .default_track(TrackType::Audio)
        .ok_or_else(|| Error::Audio("sound has no audio track".into()))?;
    let track_id = track.id;
    let params = track
        .codec_params
        .as_ref()
        .and_then(|p| p.audio())
        .ok_or_else(|| Error::Audio("sound has no audio parameters".into()))?;
    let mut decoder = symphonia::default::get_codecs()
        .make_audio_decoder(params, &AudioDecoderOptions::default())
        .map_err(fail)?;

    let mut rate = SAMPLE_RATE;
    let mut channels = 1;
    let mut samples = Vec::new();
    let mut chunk = Vec::new();
    while let Some(packet) = format.next_packet().map_err(fail)? {
        if packet.track_id != track_id {
            continue;
        }
        let buffer = decoder.decode(&packet).map_err(fail)?;
        rate = buffer.spec().rate();
        channels = buffer.spec().channels().count().max(1);
        buffer.copy_to_vec_interleaved::<f32>(&mut chunk);
        samples.extend_from_slice(&chunk);
    }
    Ok(resample_to_stereo(&samples, channels, rate))
}

/// Linear resampling to 48 kHz stereo; mono is copied to both sides and extra
/// channels are dropped.
fn resample_to_stereo(samples: &[f32], channels: usize, rate: u32) -> Vec<f32> {
    let frames = samples.len() / channels;
    let frame = |i: usize| {
        let base = i.min(frames.saturating_sub(1)) * channels;
        let left = samples[base];
        let right = if channels > 1 {
            samples[base + 1]
        } else {
            left
        };
        (left, right)
    };
    if frames == 0 {
        return Vec::new();
    }
    let out_frames = (frames as u64 * SAMPLE_RATE as u64 / rate.max(1) as u64) as usize;
    let step = rate as f64 / SAMPLE_RATE as f64;
    let mut out = Vec::with_capacity(out_frames * 2);
    for i in 0..out_frames {
        let pos = i as f64 * step;
        let j = pos.floor() as usize;
        let f = (pos - j as f64) as f32;
        let (l0, r0) = frame(j);
        let (l1, r1) = frame(j + 1);
        out.push(l0 + (l1 - l0) * f);
        out.push(r0 + (r1 - r0) * f);
    }
    out
}

/// Decoded sounds of one pack, ready to mix.
pub struct PackSounds {
    sounds: Vec<(SoundKind, Vec<f32>)>,
}

impl PackSounds {
    pub fn load(pack: SoundPack) -> Result<Self> {
        let sounds = SoundKind::ALL
            .iter()
            .map(|kind| Ok((*kind, decode(bundled(pack, *kind), "wav")?)))
            .collect::<Result<_>>()?;
        Ok(Self { sounds })
    }

    pub fn get(&self, kind: SoundKind) -> &[f32] {
        self.sounds
            .iter()
            .find(|(k, _)| *k == kind)
            .map(|(_, s)| s.as_slice())
            .unwrap_or(&[])
    }
}

/// Deterministic white noise.
struct Noise(u32);

impl Noise {
    fn next(&mut self) -> f64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 17;
        self.0 ^= self.0 << 5;
        self.0 as f64 / u32::MAX as f64 * 2.0 - 1.0
    }
}

/// A decaying sine: `(frequency Hz, decay seconds, amplitude)`.
type Partial = (f64, f64, f64);

struct Voice {
    partials: &'static [Partial],
    /// Noise burst: decay in seconds and amplitude.
    noise: (f64, f64),
    /// One-pole high-pass coefficient for the noise; higher is brighter.
    brightness: f64,
    /// A second, quieter hit after this many seconds (switch bottoming out).
    echo: Option<(f64, f64)>,
    /// The partials start at this multiple of their frequency and glide to it with
    /// this time constant in seconds, like a bubble popping.
    glide: Option<(f64, f64)>,
}

const LENGTH_SECONDS: f64 = 0.12;

fn render(voice: &Voice, pitch: f64, gain: f64, seed: u32) -> Vec<f64> {
    let rate = SAMPLE_RATE as f64;
    let len = (LENGTH_SECONDS * rate) as usize;
    let mut noise = Noise(seed);
    let mut out = vec![0.0; len];
    let hit = |out: &mut Vec<f64>, noise: &mut Noise, start: usize, level: f64| {
        let mut previous_in = 0.0;
        let mut previous_out = 0.0;
        for (i, sample) in out.iter_mut().enumerate().skip(start) {
            let t = (i - start) as f64 / rate;
            let n = noise.next();
            let high = voice.brightness * (previous_out + n - previous_in);
            previous_in = n;
            previous_out = high;
            let mut v = high * voice.noise.1 * (-t / voice.noise.0).exp();
            let cycles = match voice.glide {
                Some((from, seconds)) => t + (from - 1.0) * seconds * (1.0 - (-t / seconds).exp()),
                None => t,
            };
            for (frequency, decay, amplitude) in voice.partials {
                let phase = std::f64::consts::TAU * frequency * pitch * cycles;
                v += phase.sin() * amplitude * (-t / decay).exp();
            }
            *sample += v * level;
        }
    };
    hit(&mut out, &mut noise, 0, 1.0);
    if let Some((delay, level)) = voice.echo {
        hit(&mut out, &mut noise, (delay * rate) as usize, level);
    }
    let attack = (0.0006 * rate) as usize;
    let release = (0.02 * rate) as usize;
    for (i, sample) in out.iter_mut().enumerate() {
        let fade_in = (i as f64 / attack as f64).min(1.0);
        let fade_out = ((len - i) as f64 / release as f64).min(1.0);
        *sample *= gain * fade_in * fade_out;
    }
    out
}

/// The 16-bit mono samples of one bundled sound.
pub fn synthesize(pack: SoundPack, kind: SoundKind) -> Vec<i16> {
    const SOFT_DOWN: Voice = Voice {
        partials: &[
            (190.0, 0.03, 0.4),
            (640.0, 0.018, 0.35),
            (1_350.0, 0.008, 0.15),
        ],
        noise: (0.004, 0.3),
        brightness: 0.45,
        echo: None,
        glide: None,
    };
    const SOFT_UP: Voice = Voice {
        partials: &[(260.0, 0.016, 0.25), (820.0, 0.01, 0.25)],
        noise: (0.003, 0.2),
        brightness: 0.45,
        echo: None,
        glide: None,
    };
    const CLICK_DOWN: Voice = Voice {
        partials: &[
            (2_200.0, 0.012, 0.35),
            (3_700.0, 0.008, 0.25),
            (900.0, 0.01, 0.2),
        ],
        noise: (0.0025, 0.9),
        brightness: 0.9,
        echo: None,
        glide: None,
    };
    const CLICK_UP: Voice = Voice {
        partials: &[(2_600.0, 0.008, 0.25), (4_200.0, 0.006, 0.18)],
        noise: (0.002, 0.6),
        brightness: 0.92,
        echo: None,
        glide: None,
    };
    const MECHANICAL_DOWN: Voice = Voice {
        partials: &[
            (1_100.0, 0.04, 0.22),
            (300.0, 0.03, 0.45),
            (4_800.0, 0.006, 0.1),
        ],
        noise: (0.002, 0.8),
        brightness: 0.85,
        echo: Some((0.007, 0.6)),
        glide: None,
    };
    const MECHANICAL_UP: Voice = Voice {
        partials: &[(1_400.0, 0.03, 0.2), (380.0, 0.02, 0.3)],
        noise: (0.0018, 0.6),
        brightness: 0.85,
        echo: None,
        glide: None,
    };

    const TRACKPAD_DOWN: Voice = Voice {
        partials: &[
            (330.0, 0.012, 0.5),
            (1_750.0, 0.005, 0.3),
            (3_100.0, 0.003, 0.12),
        ],
        noise: (0.0015, 0.35),
        brightness: 0.6,
        echo: None,
        glide: None,
    };
    const TRACKPAD_UP: Voice = Voice {
        partials: &[(420.0, 0.008, 0.35), (2_100.0, 0.004, 0.2)],
        noise: (0.001, 0.25),
        brightness: 0.6,
        echo: None,
        glide: None,
    };
    const POP_DOWN: Voice = Voice {
        partials: &[(720.0, 0.03, 0.6), (1_440.0, 0.012, 0.12)],
        noise: (0.001, 0.15),
        brightness: 0.7,
        echo: None,
        glide: Some((0.55, 0.01)),
    };
    const POP_UP: Voice = Voice {
        partials: &[(1_050.0, 0.02, 0.45), (2_100.0, 0.008, 0.1)],
        noise: (0.001, 0.1),
        brightness: 0.7,
        echo: None,
        glide: Some((0.6, 0.008)),
    };
    const TICK_DOWN: Voice = Voice {
        partials: &[(5_200.0, 0.004, 0.3), (7_900.0, 0.0025, 0.18)],
        noise: (0.0008, 0.5),
        brightness: 0.97,
        echo: None,
        glide: None,
    };
    const TICK_UP: Voice = Voice {
        partials: &[(6_300.0, 0.003, 0.22)],
        noise: (0.0006, 0.35),
        brightness: 0.97,
        echo: None,
        glide: None,
    };

    let (voice, gain) = match (pack, kind) {
        (SoundPack::SoftTap, SoundKind::LeftDown | SoundKind::RightDown) => (&SOFT_DOWN, 0.8),
        (SoundPack::SoftTap, _) => (&SOFT_UP, 0.55),
        (SoundPack::MouseClick, SoundKind::LeftDown | SoundKind::RightDown) => (&CLICK_DOWN, 0.7),
        (SoundPack::MouseClick, _) => (&CLICK_UP, 0.5),
        (SoundPack::Mechanical, SoundKind::LeftDown | SoundKind::RightDown) => {
            (&MECHANICAL_DOWN, 0.75)
        }
        (SoundPack::Mechanical, _) => (&MECHANICAL_UP, 0.5),
        (SoundPack::TrackpadTap, SoundKind::LeftDown | SoundKind::RightDown) => {
            (&TRACKPAD_DOWN, 0.75)
        }
        (SoundPack::TrackpadTap, _) => (&TRACKPAD_UP, 0.5),
        (SoundPack::Pop, SoundKind::LeftDown | SoundKind::RightDown) => (&POP_DOWN, 0.7),
        (SoundPack::Pop, _) => (&POP_UP, 0.5),
        (SoundPack::Tick, SoundKind::LeftDown | SoundKind::RightDown) => (&TICK_DOWN, 0.6),
        (SoundPack::Tick, _) => (&TICK_UP, 0.45),
    };
    let right = matches!(kind, SoundKind::RightDown | SoundKind::RightUp);
    let pitch = match (pack, right) {
        (_, false) => 1.0,
        (SoundPack::MouseClick, true) => 0.85,
        (_, true) => 1.2,
    };
    let seed = 0x9e37_79b9 ^ (pack as u32) << 8 ^ (kind as u32);
    render(voice, pitch, gain, seed)
        .into_iter()
        .map(|v| (v.clamp(-1.0, 1.0) * i16::MAX as f64).round() as i16)
        .collect()
}

/// A WAV file with a pack's left-button press, then its release, for previewing it.
pub fn preview(pack: SoundPack) -> Vec<u8> {
    let mut samples = synthesize(pack, SoundKind::LeftDown);
    samples.resize(samples.len() + SAMPLE_RATE as usize / 40, 0);
    samples.extend(synthesize(pack, SoundKind::LeftUp));
    wav(&samples)
}

/// A 16-bit mono PCM WAV file.
pub fn wav(samples: &[i16]) -> Vec<u8> {
    let data_len = (samples.len() * 2) as u32;
    let mut out = Vec::with_capacity(44 + data_len as usize);
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&(36 + data_len).to_le_bytes());
    out.extend_from_slice(b"WAVEfmt ");
    out.extend_from_slice(&16u32.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes());
    out.extend_from_slice(&SAMPLE_RATE.to_le_bytes());
    out.extend_from_slice(&(SAMPLE_RATE * 2).to_le_bytes());
    out.extend_from_slice(&2u16.to_le_bytes());
    out.extend_from_slice(&16u16.to_le_bytes());
    out.extend_from_slice(b"data");
    out.extend_from_slice(&data_len.to_le_bytes());
    for s in samples {
        out.extend_from_slice(&s.to_le_bytes());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_sounds_match_the_generator() {
        for pack in SoundPack::ALL {
            for kind in SoundKind::ALL {
                assert!(
                    bundled(pack, kind) == wav(&synthesize(pack, kind)).as_slice(),
                    "{pack:?} {kind:?} is stale; run `make sounds`"
                );
            }
        }
    }

    #[test]
    fn decodes_bundled_wav_to_stereo() {
        let samples = synthesize(SoundPack::Mechanical, SoundKind::LeftDown);
        let decoded = decode(bundled(SoundPack::Mechanical, SoundKind::LeftDown), "wav").unwrap();
        assert_eq!(decoded.len(), samples.len() * 2);
        for (i, s) in samples.iter().enumerate().step_by(97) {
            let expected = *s as f32 / 32768.0;
            assert!((decoded[2 * i] - expected).abs() < 1e-4);
            assert_eq!(decoded[2 * i], decoded[2 * i + 1]);
        }
    }

    #[test]
    fn sounds_are_distinct_and_audible() {
        let mut seen = Vec::new();
        for pack in SoundPack::ALL {
            for kind in SoundKind::ALL {
                let samples = synthesize(pack, kind);
                let peak = samples.iter().map(|s| s.unsigned_abs()).max().unwrap();
                assert!(peak > 3_000, "{pack:?} {kind:?} peak {peak}");
                assert!(!seen.contains(&samples));
                seen.push(samples);
            }
        }
    }

    /// Loudest 5 ms RMS level in dBFS of the part above about 400 Hz, what laptop
    /// speakers play.
    fn audible_level(samples: &[i16]) -> f64 {
        let k = (-std::f64::consts::TAU * 400.0 / SAMPLE_RATE as f64).exp();
        let mut stages = [(0.0, 0.0); 2];
        let high: Vec<f64> = samples
            .iter()
            .map(|s| {
                let mut x = *s as f64 / 32768.0;
                for (previous_in, previous_out) in &mut stages {
                    let y = k * (*previous_out + x - *previous_in);
                    *previous_in = x;
                    *previous_out = y;
                    x = y;
                }
                x
            })
            .collect();
        let window = SAMPLE_RATE as usize / 200;
        high.windows(window)
            .step_by(window / 4)
            .map(|w| 10.0 * (w.iter().map(|x| x * x).sum::<f64>() / window as f64).log10())
            .fold(f64::MIN, f64::max)
    }

    #[test]
    fn every_pack_is_audible_on_laptop_speakers() {
        for pack in SoundPack::ALL {
            for kind in SoundKind::ALL {
                let level = audible_level(&synthesize(pack, kind));
                assert!(level > -32.0, "{pack:?} {kind:?}: {level:.1} dB");
            }
        }
    }

    #[test]
    fn preview_plays_press_then_release() {
        let down = synthesize(SoundPack::Pop, SoundKind::LeftDown);
        let preview = decode(&preview(SoundPack::Pop), "wav").unwrap();
        let up_starts = down.len() + SAMPLE_RATE as usize / 40;
        let up = synthesize(SoundPack::Pop, SoundKind::LeftUp);
        assert_eq!(preview.len(), (up_starts + up.len()) * 2);
        assert!((preview[2 * up_starts + 200] - up[100] as f32 / 32768.0).abs() < 1e-4);
    }

    #[test]
    fn resamples_mono_to_stereo() {
        let out = resample_to_stereo(&[0.0, 1.0, 0.0, -1.0], 1, 24_000);
        assert_eq!(out.len(), 16);
        assert_eq!(&out[..4], &[0.0, 0.0, 0.5, 0.5]);
    }

    #[test]
    fn right_clicks_use_left_sounds_unless_separate() {
        assert_eq!(
            SoundKind::for_click(MouseButton::Right, true, false),
            SoundKind::LeftDown
        );
        assert_eq!(
            SoundKind::for_click(MouseButton::Right, false, true),
            SoundKind::RightUp
        );
        assert_eq!(
            SoundKind::for_click(MouseButton::Left, true, true),
            SoundKind::LeftDown
        );
    }
}
